version: '3'
services:
  portfolio:
    build: .
    image: portfolio:2023
    container_name: portfolio
    restart: unless-stopped
    env_file: .env
    environment:
      - NODE_ENV=production
    ports:
      - "3003:3003"
    volumes:
      - .:/home/node/app
    command: node server.js
