import type { NextPageWithLayout } from "./_app";
import Head from "next/head";
import { Container } from "@nextui-org/react";

const Index: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Still-Routley Dev - Home</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container css={{ backgroundColor: "$background" }}>
        <h1>Here is the body</h1>
        <p></p>
      </Container>
    </>
  );
};

export default Index;
